server:
  port: 8090

spring.data.mongodb:
  host: localhost
  port: 27017
  database: admin
  username: mongoadmin
  password: mongoadmin

logging:
  level:
    root: info
    poc: debug

springdoc:
  packagesToScan: poc.mongodb.adapter.rest
  show-actuator: true
